### ISSUE TITLE
Import data from old P1mon installation doesn't work

### ISSUE THREAD

**Issue by molis83** [intelwolf/p1monitor#1]
First off; Thanks for this great work! 

I managed to get everything up and running on a Synology nas (that wasn't straight forward, because you can't mount tmpfs and/or devices). Using Pontainer I managed to get everything working. After that you need to make sure that your /dev/ttyUSB0 is chmod to 777.

Okay, so far so good. I now have a running install in Docker that receives data from the P1 cable. 

Next step: Import 1,5 years of data from my old p1mon install.

I exported the database (with the export button) on the Raspberry. Next: I click the import button in the docker install and choose the file. Nothing happens. 

I tried the same on my old install, to make sure the fault isn't in P1mon. But overthere it immediatly starts to import the file.

I suspect it has something to do with the upload location of the import file, is that possible?

**Comment by intelwolf** [comment]
Thanks for reporting.

I checked and could reproduce the issue. Due to missing directories in the structure import as well as export functions were failing. I updated the directory structure and owner status of a number of other files in version 1.3.1c. I have tested on my instance and that seems to be functioning fine now so let me know if this is working now. 

New image is pushed to docker hub.

**Comment by molis83** [comment]
I'm a small step further...

Now I get the 'import status' screen, but it keeps hanging on: "Even geduld aub, verwerking start over enkele seconden'.

**Comment by molis83** [comment]
Another thing: It looks like every time I stop/start the container new Database files are created:
![Screenshot 2021-08-26 201653](https://user-images.githubusercontent.com/6142487/131015033-104f0406-c7e6-4494-9ce2-367e4e0f2e10.png)

**Comment by intelwolf** [comment]
I had a sort-a-like experience when running in a VM. Could you check if the P1Watchdog service is running? And if not, post the error message it spawns if you start it manually from p1mon/scripts?

**Comment by intelwolf** [comment]
> Another thing: It looks like every time I stop/start the container new Database files are created:
> 
> ![Screenshot 2021-08-26 201653](https://user-images.githubusercontent.com/6142487/131015033-104f0406-c7e6-4494-9ce2-367e4e0f2e10.png)
> 
> 
I expect these to be the backup files that are maintained by the P1 software itself. I will check on that too

**Comment by molis83** [comment]
> I had a sort-a-like experience when running in a VM. Could you check if the P1Watchdog service is running? And if not, post the error message it spawns if you start it manually from p1mon/scripts?

It wasn't running and when I run it it gives:

root@p1mon:/p1mon/scripts# python3 P1Watchdog.py
2021-08-26 20:26:07 Info: Start van programma.
2021-08-26 20:26:07 Info: Start van programma P1DbCopy.
2021-08-26 20:26:07 Info: Main: wordt uitgevoerd als user -> root
2021-08-26 20:26:07 Info: MainProg: database tabel: status succesvol geopend.
2021-08-26 20:26:08 Info: MainProg: database tabel config succesvol geopend.
2021-08-26 20:26:08 Info: setSambaMode SAMBA mode=uit
smbd: unrecognized service
2021-08-26 20:26:08 Error: setSambaMode SAMBA (bestand delen) service stoppen gefaald.
2021-08-26 20:26:08 Info: MainProg: System ID zetten in configuratie database: CB64-F0F3-7455-1428-F6C2
Traceback (most recent call last):
  File "P1Watchdog.py", line 1076, in <module>
    MainProg()
  File "P1Watchdog.py", line 125, in MainProg
    getCpuTemperature() 
  File "P1Watchdog.py", line 820, in getCpuTemperature
    tfile = open('/sys/class/thermal/thermal_zone0/temp','r')
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/thermal/thermal_zone0/temp'

**Comment by intelwolf** [comment]
Ah perfect,
That's exactly the same issue as I had. T is searching for the CPU temperature but that is not accessible. I already have the fix ready for that and will adjust the code tomorrow

**Comment by molis83** [comment]
Great! Please let me know if you need anything more from me.

**Comment by intelwolf** [comment]
I updated the code to prevent this error. It is trying to read the CPU temperature but that is not available in VM's and some other instances.
You need to add the environment variable DISABLECPUTEMP=true in your docker compose file to have CPU temperature measuring disabled

**Comment by molis83** [comment]
Thanks, dataimport seems to work now (after manually starting P1Watchdog.py), but is super slow..

I'm starting to think that P1mon ask a bit more then a synology nas can handle (although it's a 220+ model):
![image](https://user-images.githubusercontent.com/6142487/131166725-f425e9ca-fbb0-46ed-9671-673408017101.png)

Next error when running P1Watchdog.py:
![image](https://user-images.githubusercontent.com/6142487/131166538-96f52907-96c3-4a27-8d2b-8949f8218133.png)

[edit] The process crashes: 
![image](https://user-images.githubusercontent.com/6142487/131167626-938763b8-fc7b-443e-b6ae-d9926d3301f6.png)
[/edit]

![image](https://user-images.githubusercontent.com/6142487/131168043-a8c6445a-ee18-4c46-b7c2-c4638888425e.png)

Maybe I should try to install docker on my Raspberry, and use your files there.. I like it that updating is fixed without changing SDcards etc.. But wanted to get rid of the Rapsberry (all my other containers are running like a charm on the nas).

**Comment by intelwolf** [comment]
The smbd service is  not installed so that error makes sense. It does not crash the service though but I'll need to clean it up some time.
Memory consumption cannot be measure within a docker container as it will dimension itself (if not restricted), so these values are not usable and will usually be around 95%. I noticed that importing the records is a slow process but after thats done it should all function fine. Since I see a ^C and SIGINT, did you interrupt one of the services?
I'm running this container myself on a Linux laptop without any crashes for half a year already without noticeable impact so it should be good.
I have not build an image for Arm yet but will took a look on that too

**Comment by molis83** [comment]
I didn't interrupt anything (on purpose anyway). I'll try to import again, but it's strange I have to run P1Watchdog.py by hand at import, isn't it? 

BTW, it isn't an ARM processor (Intel Celeron J4025)

 
![image](https://user-images.githubusercontent.com/6142487/131180399-fdde6e98-3486-4021-9688-e062900e7779.png)

**Comment by intelwolf** [comment]
No, using the latest build from this morning it should not be necessary to start any service manually. The import process should be fully functioning using the web interface. 
Maybe you should start all over again (if not done already and you don't need the data) by deleting the alldata directory completely, start the new container and start the import process from scratch
