### ISSUE TITLE
Log rotation socat

### ISSUE THREAD

**Issue by topjor** [intelwolf/p1monitor#4]
When diagnosing an issue with socat dropping and not connecting back, I noticed the logs for socat are not rotated.
Because of the verbose options (`-d -d -d`) it will log every time it receives data. The log file of around a months worth of data is almost 400MB for reference in tuning this.

I an not sure if it would also be a good option to drop some of the verbosity by default when using socat. One could always add these flags back for debugging rough the socat options variable.

I might take a look at submitting a PR fixing this myself if I got the time this week.
(also you have not pushed back to github with v1.7.0d, github is still at v1.7.0a, and the `entrypoint.sh` looks to be missing, or I am blind)

**Comment by intelwolf** [comment]
Sounds logical and as I'm not using it myself I didn't notice. I will take a look at modifying that logging at the V2 version. Might change the logging to parameters perhaps. 
The entrypoint.sh file is located in the addons folder by the way. 
Apologize for not responding earlier, for some reason I'm not notified on new issues

**Comment by topjor** [comment]
No problem, I forgot it myself.

I had to shelf using socat as it stopped working after a while a few times, without dropping the connection, so it does not restart as it thinks its still working. Also had some issues with the host providing the serial over tcp, so I imagine that is the problem of it breaking is there most likely, not this container.

I might have one suggestion to catch such an issue (container side): Also check if the serial port is reporting working correctly inside P1, otherwise restarting socat, though I have no idea if that would be even useful, I always restarted both socat (source side) and the container, so I can't rule anything out.

**Comment by intelwolf** [comment]
Modified loggig to fatal and error only in next version (was fatal, error, warning, notice, info, and debug). Will check later for the restarting part
