### ISSUE TITLE
No "actueel verbruik"

### ISSUE THREAD

**Issue by cazure-n00b** [intelwolf/p1monitor#9]
Just installed my this on my Synology NAS.
Got everything working in Docker, I can access the portal. But it seems it's not showing any real data right now.
How to troubleshoot?

Synology NAS is connected to my network
P1 cable directly into the USB of my  NAS.

**Comment by intelwolf** [comment]
Quit some people have this working on their Synology NAS but it also depends on what type you have. You can also check here if this may help you: https://forum.p1mon.nl/viewtopic.php?p=2732#p2732

**Comment by cazure-n00b** [comment]
Hi Intelwolf,

I get this error now, check on the forum as well. But can't find it:
WARNING - check_serial: serial port niet te openen (/dev/ttyUSB0) is de USB serial kabel aangesloten? melding:("Could not configure port: (25, 'Inappropriate ioctl for device')",)
CRITICAL - main_prod: seriele poort niet gevonden, is de kabel aangesloten?

You experienced this as well?

**Comment by intelwolf** [comment]
Unfortunately I do not have a Synology and the only times I experienced that was when the configuration of the serial port was incorrect or unreachable. The forum is a good source of users so let's follow that.

**Comment by intelwolf** [comment]
Closing as this is discussed at forum.p1mon.nl
